"""
开发环境，配置文件
"""


"""
Django settings for dailyfresh project.

Generated by 'django-webmaster startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import sys
from .base import *

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%k^nxv&(+ys^_s5lhw@vqdv$x4guu$wp85$$zn8m$bosr7z6vv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '192.168.85.128',
    '127.0.0.1',
]


# FastDFS设置-客户端配置文件
FDFS_CLIENT_CONF = './utils/fdfs/client/development_client.conf'

# 设置fdfs存储服务器上nginx的IP和端口号
FDFS_URL = 'http://192.168.85.128:8888/'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'pyb_web',
        'USER': 'root',
        'PASSWORD': os.environ['PASSWORD'],
        'HOST': '127.0.0.1',
        'PORT': 3306,
    }
}

# # gjango 的缓存配置
# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/10',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         }
#     }
# }


# from celery.schedules import crontab
# CELERY_BEAT_SCHEDULE = {
#         'fetch_news_every-1-hour': {
#             'task': 'news.tasks.fetch_all_news',
#             'schedule': crontab(minute=0, hour='*/1'),
#         }
# }
#

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.qq.com'
# EMAIL_PORT = 465
# # 发送邮件的邮箱
# EMAIL_HOST_USER = '2679771017@qq.com'
# # 授权码
# EMAIL_HOST_PASSWORD = 'kwqjcypjkkweecah'
# # 收件人看到的发件人
# EMAIL_FROM = '天天生鲜<2679771017@qqcom>'
EMAIL_USE_SSL = True
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = '2679771017@qq.com'  # 帐号
EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']  # 密码
EMAIL_FROM = '天天生鲜<2679771017@qq.com>'

