# Generated by Django 2.1.7 on 2019-04-11 05:02

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(max_length=100, verbose_name='文章描述'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='文章内容'),
        ),
    ]
