# Generated by Django 2.1.7 on 2019-05-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default=None, upload_to='static/avatar/fengmian.jpg', verbose_name='封面图片'),
        ),
    ]
