# Generated by Django 2.1.7 on 2019-04-12 02:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190411_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='评论内容'),
        ),
    ]
