# Generated by Django 2.1.7 on 2019-05-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190531_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/avatar/fengmian.jpg', verbose_name='封面图片'),
        ),
    ]
