# Generated by Django 2.1.7 on 2019-04-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_article_mod_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='avatar/default.png', upload_to='avatar/%Y/%m', verbose_name='封面图片'),
        ),
    ]
