# Generated by Django 2.1.7 on 2019-04-18 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
