# Generated by Django 2.1.7 on 2019-04-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
