# Generated by Django 2.1.7 on 2019-04-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190419_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creed',
            field=models.CharField(blank=True, default=None, max_length=300, verbose_name='个人信条'),
        ),
    ]
