# Generated by Django 2.1.7 on 2019-04-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user_creed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pid',
            field=models.IntegerField(max_length=50, verbose_name='父级评论id'),
        ),
    ]
