# Generated by Django 2.1.7 on 2019-05-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20190419_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, max_length=200, null=True, upload_to='static/avatar/default.png', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='creed',
            field=models.CharField(blank=True, default='好好学习，天天向上！', max_length=300, verbose_name='个人信条'),
        ),
    ]
